# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Desplegará cuando se haga push a la rama 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Ejecutar en un servidor Linux

    steps:
      - name: Checkout code # Paso 1: Clonar el repositorio
        uses: actions/checkout@v3 # Usa la versión 3 de la acción de checkout

      - name: Setup Node.js # Paso 2: Configurar Node.js
        uses: actions/setup-node@v3 # Usa la versión 3 de setup-node
        with:
          node-version: '20' # Usa la versión 20 de Node.js

      - name: Install dependencies # Paso 3: Instalar las dependencias del proyecto
        run: npm install # Ejecuta el comando npm install

      - name: Build application # Paso 4: Compilar la aplicación React con Vite
        run: npm run build # Ejecuta el comando de build definido en package.json

      # ¡¡¡NUEVO PASO CRÍTICO!!!
      # Este paso listará el contenido de la carpeta 'dist' después del build.
      # La salida de este comando la veremos en los logs de GitHub Actions.
      - name: List dist contents # Paso 5: Listar contenido de la carpeta de salida
        run: ls -lR dist/ # 'ls -lR' lista recursivamente todos los archivos y carpetas dentro de 'dist' con detalles

      - name: Deploy to GitHub Pages # Paso 6: Desplegar a GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # Usa la acción de peaceiris para gh-pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Token de GitHub para permisos
          publish_dir: ./dist # La carpeta que se debe publicar
          publish_branch: gh-pages # La rama donde se publicará (GitHub Pages)
          allow_empty_commit: false # No permitir commits vacíos
          keep_files: false # Borrar archivos existentes en gh-pages antes de copiar
          force_orphan: false # Crear una nueva rama gh-pages si no existe
          enable_jekyll: false # No habilitar Jekyll
          disable_nojekyll: false # No deshabilitar el .nojekyll (por defecto se crea)
          exclude_assets: .github # Excluir la carpeta .github del despliegue
